services:
  shiori:
    image: ghcr.io/go-shiori/shiori:latest
    container_name: shiori
    ports:
      - "8080:8080"
    volumes:
      - shiori-data:/shiori/data
    environment:
      - SHIORI_DIR=/shiori/data
      - SHIORI_PORT=8080
    restart: unless-stopped

volumes:
  shiori-data: